# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=40, verbose_name='用户密码'),
        ),
    ]
