# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.IntegerField(choices=[(2, '微信支付'), (3, '支付宝'), (1, '货到付款'), (4, '银联支付')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.IntegerField(choices=[(2, '待发货'), (3, '待收货'), (5, '已完成'), (4, '待评价'), (1, '待支付')], default=1, verbose_name='订单进程'),
        ),
    ]
